name: Build Flipper App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4

      - name: Clone Flipper Zero Firmware
        run: |
          git clone --recursive https://github.com/flipperdevices/flipperzero-firmware.git
          cp -r applications_user/ flipperzero-firmware/
          cd flipperzero-firmware
          ./fbt applications_user/credit_tool

      - name: Debug list build folder
        run: ls -R flipperzero-firmware/build/f7-apps/

      - name: Upload compiled .fap
        uses: actions/upload-artifact@v4
        with:
          name: compiled-fap
          path: flipperzero-firmware/build/f7-apps/**/*.fap
